---
apiVersion: v1
kind: Secret
metadata:
  name: product-app-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/janus-backstage/product-app-gitops.git
